name: Lint and check formatting
on: pull_request

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: PHP Code Sniffer (php-actions)
        uses: php-actions/phpcs@v1.0.0
        with:
          php_version: 8.1
          path: .
          standard: phpcs.xml
